# MySQL.  Versions 4.1 and 5.0 are recommended.
#
# Install the MYSQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html

development:
  adapter: postgresql
  encoding: unicode
  reconnect: false
  database: opine_development
  pool: 5
  username: dromanovsky
  password: 1
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: opine_test
  pool: 5
  username: dromanovsky
  password: 1
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: opine_production
  pool: 10
  username: opine
  password: <%= ENV['DATABASE_PASSWORD'] %>
  socket: /var/run/mysqld/mysqld.sock