# MySQL.  Versions 4.1 and 5.0 are recommended.
#
# Install the MYSQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html

development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: opine_development
  pool: 5
  username: root
  password: root
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: opine_test
  pool: 5
  username: root
  password: root
  host: localhost

staging:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: opine_production
  pool: 10
  username: root
  password: kAcXslQuJe2SodnAvqCJcbLa
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: opine_production
  pool: 10
  username: opine
  password: <%= ENV['DATABASE_PASSWORD'] %>
  socket: /var/run/mysqld/mysqld.sock